<?php
abstract class RocketrBlacklistMethod {
    const ALLOW_ALL_BUYERS_TO_PURCHASE = 0;
    const ALLOW_ALL_BUYERS_TO_PURCHASE_EXCEPT_MY_BLACKLIST = 1;
    const ALLOW_ALL_BUYERS_TO_PURCHASE_EXCEPT_GLOBAL_BLACKLIST = 2;
    const ALLOW_ALL_BUYERS_TO_PURCHASE_EXCEPT_PROXIES_AND_VPNS = 3;
    const ALLOW_ALL_BUYERS_TO_PURCHASE_EXCEPT_MY_BLACKLIST_AND_PROXIES_AND_VPNS = 4;
    const ALLOW_ALL_BUYERS_TO_PURCHASE_EXCEPT_GLOBAL_BLACKLIST_AND_PROXIES_AND_VPNS = 5;
}

?>